site_name: Science Camp 2024 - Workshop Tutorials
site_url: https://science-camp-tui.github.io/tutorials/
use_directory_urls: false
plugins: []

nav:
  - Home: index.md
  - Starter Tutorial: starter/index.md
  - Machine Learning Tutorials: 
    - Introduction: machine-learning/index.md
    - Audio Processing: machine-learning/audio-processing.md
    - Bird Classification: machine-learning/bird-classification.md
    - Code-Snippets: machine-learning/code-snippets.md
  - IoT System Tutorial: system/index.md
    - Code-Snippets: machine-learning/code-snippets.md
  - Dashboard Tutorials: dashboard/index.md
 

theme:
    name: material
    features:
        - navigation.path
        - toc.integrate  

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

